version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    command: script/puma
    env_file: ".env"
    ports:
      - 2300:2300
volumes:
  bundle_path:
  node_modules:
