#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db…"
hanami db create

hanami db create -e test
hanami db reset -e test

hanami db migrate
